---

- name: get service facts
  service_facts:

- name: opent port
  firewalld:
    port: "{{ node_exporter_listen_port }}/tcp"
    permanent: yes
    state: enabled
  when: ansible_facts.services['firewalld.service']['state'] == 'running'
  notify: reload firewalld
