---

- name: Create the node_exporter group
  group:
    name: "{{ node_exporter_group }}"
    state: present

- name: Create the node_exporter user
  user:
    name: "{{ node_exporter_user }}"
    group: "{{ node_exporter_group }}"
    shell: /usr/sbin/nologin

- name: Download node_exporter binary to local folder
  get_url:
    url: "{{ node_exporter_download_url }}"
    dest: "/tmp/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
  register: _download_binary
  retries: 5
  delay: 10
  until: _download_binary is succeeded

- name: Unpack node_exporter binary
  unarchive:
    src: "/tmp/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
    dest: "/tmp/"
    creates: "/tmp/node_exporter-{{ node_exporter_version }}.linux-amd64/node_exporter"
    remote_src: yes

- name: Propagate node_exporter binaries
  copy:
    src: "/tmp/node_exporter-{{ node_exporter_version }}.linux-amd64/node_exporter"
    dest: "/usr/local/bin/node_exporter"
    mode: 0755
    owner: root
    group: root
    remote_src: yes
- name: create systemd service unit
  template:
    src: node_exporter.service.j2
    dest: /etc/systemd/system/node_exporter.service
    owner: root
    group: root
    mode: 0644
  notify: restart node_exporter

