- name: Install Java
  yum: 
    name: "{{ java_packages }}"
    state: present 
  
- name: Install elastic
  yum:
    name: https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.6.1-x86_64.rpm
    state: present
    
- name: Set configuration
  template: 
    src: elasticsearch.yml.j2
    dest: /etc/elasticsearch/elasticsearch.yml
    mode: 0755
    owner: root
    group: elasticsearch
  notify: restart_elastic